version: "3.7"
services:
  app:
    image: jksantos/php8.3.6:1.1
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../project/:/var/www
      - /home/${USER}/.ssh:/home/vscode/.ssh:ro
      - ../.docker/app/zshrc:/home/vscode/.zshrc
    networks:
      - network1
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      TZ: "America/Sao_Paulo"

  db:
    image: mysql:8.0.36
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: laravel
      MYSQL_USER: laravel
      # SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: "America/Sao_Paulo"
    volumes:
      - ../.docker/mysql:/var/lib/mysql
    networks:
      - network1

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../project/:/var/www
      - ../.docker/nginx/conf.d:/etc/nginx/conf.d
      - ../.docker/nginx/logs:/var/log/nginx
      - ../.docker/nginx/ssl:/etc/ssl/docker
    networks:
      - network1

networks:
  network1:
    name: vetsoft-sat
    external: true
